import { defineConfig, lazyPlugins } from 'vite-plus'
import { voidPlugin } from 'void'

// This is a server-only Void app (API routes under `routes/`, no client bundle).
// `voidPlugin()` infers the Cloudflare bindings, loads `.env*`, and produces the
// deployable Worker for `void deploy`.
export default defineConfig({
  staged: {
    '*': 'vp check --fix',
  },
  fmt: {
    singleQuote: true,
    semi: false,
  },
  lint: {
    jsPlugins: [{ name: 'vite-plus', specifier: 'vite-plus/oxlint-plugin' }],
    rules: { 'vite-plus/prefer-vite-plus-imports': 'error' },
    options: { typeAware: true, typeCheck: true },
  },
  // `vp pack` bundles the publish-preview GitHub Action into a single
  // self-contained file (committed as dist/index.mjs) so the consumer needs no
  // install step. It pulls in nanotar and the Worker's own rewrite/digest
  // modules, so CI produces exactly the artifacts the Worker describes. Run
  // `vp run build:action` after changing the action or any module it imports.
  pack: {
    entry: { index: './.github/actions/publish-preview/src/index.ts' },
    outDir: '.github/actions/publish-preview/dist',
    format: 'esm',
    platform: 'node',
    target: 'node22',
    fixedExtension: true,
    // The action runs with no install step, so every dependency must land in
    // the bundle (node builtins stay external); onlyBundle: false silences the
    // per-dependency bundling hint.
    deps: { alwaysBundle: /./, onlyBundle: false },
    banner: '// GENERATED by `vp run build:action` (vp pack), do not edit.',
  },
  plugins: lazyPlugins(() => [voidPlugin()]),
})
