#!/usr/bin/env node
// Bundle the publish-preview GitHub Action into a single self-contained file
// (committed as dist/index.mjs) so the consumer needs no install step. It pulls
// in nanotar and the Worker's own rewrite/digest modules, so CI produces exactly
// the artifacts the Worker describes. Run after changing the action or any module
// it imports: `pnpm build:action`.
import { build } from 'esbuild'

const outfile = '.github/actions/publish-preview/dist/index.mjs'

await build({
  entryPoints: ['.github/actions/publish-preview/src/index.ts'],
  outfile,
  bundle: true,
  platform: 'node',
  format: 'esm',
  target: 'node20',
  banner: {
    js: '// GENERATED by scripts/build-action.mjs — do not edit. Run `pnpm build:action`.',
  },
})

console.log(`built ${outfile}`)
